### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ghost** [BritishAmateurTelevisionClub/eshail-ghy-wb-fft-airspy#2]
Where do you config the 8Mhz bandwidth?
I want to increase it to the full 10Mhz....

**Comment by philcrump** [comment]
The 0.1 and 0.9 in the following line select the middle 0.8 of the FFT to be sent to the browser. The airspy samples the full bandwidth but the RF/FFT response rolls off too much at the edges to be particularly useful.

https://github.com/BritishAmateurTelevisionClub/eshail-ghy-wb-fft-airspy/blob/master/main.c#L309

Feel free to email me rather than posting questions as issues.
